# Generated by Django 4.2.7 on 2023-12-04 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"managed": True},
        ),
    ]
