# Generated by Django 4.2.7 on 2023-11-29 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="read",
            new_name="unopened",
        ),
    ]
