# Generated by Django 4.2.7 on 2023-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_rename_read_message_unopened"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="message",
            name="subject",
        ),
        migrations.AlterField(
            model_name="message",
            name="unopened",
            field=models.BooleanField(default=True),
        ),
    ]
