# Generated by Django 4.2.7 on 2023-12-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0004_conversation_message_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="unopened",
        ),
        migrations.AddField(
            model_name="message",
            name="receiver_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_read",
            field=models.BooleanField(default=False),
        ),
    ]
