# Generated by Django 4.2.7 on 2023-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0005_remove_message_unopened_message_receiver_read_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="receiver_read",
            new_name="read",
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_read",
            field=models.BooleanField(default=True),
        ),
    ]
