# Generated by Django 4.2.7 on 2023-12-12 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0006_rename_receiver_read_message_read_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="sender_read",
        ),
    ]
