# Generated by Django 4.2.7 on 2023-12-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0007_remove_message_sender_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="read",
            new_name="receiver_read",
        ),
        migrations.AddField(
            model_name="message",
            name="sender_read",
            field=models.BooleanField(default=True),
        ),
    ]
