# Generated by Django 4.2.7 on 2023-12-22 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_remove_post_likes_remove_post_tags_delete_like_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
